# Generated by Django 2.1.5 on 2022-09-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=30, null=True)),
                ('last', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.IntegerField()),
                ('message', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_caption', models.CharField(default='', help_text='enter a caption', max_length=500)),
                ('post_img', models.ImageField(default='', upload_to='Websit/media')),
            ],
        ),
    ]
